-- 1ª CONSULTA
SELECT c.NOME, c.END_RUA, c.END_NUM, c.END_BAIRRO, c.END_CIDADE, c.END_CEP
FROM CLIENTE c, CLIENTE i
WHERE i.NOME = 'João' and i.SOBRENOME = 'da Silva' and c.CLIENTE_INDICA = i.CODCLI;

-- 2ª Consulta
SELECT CNPJ, NOME, EMAIL
FROM FORNECEDOR
WHERE HOME_PAGE IS NULL;

-- 3ª Consulta
SELECT DISTINCT C.CODCLI
FROM CLIENTE C
JOIN ORDEM_DE_COMPRA OC ON C.CODCLI = OC.CODIGO_CLIENTE
JOIN NOTA_FISCAL NF ON OC.CODORDEM = NF.COD_ORDEM_COMPRA
WHERE TO_NUMBER(TO_CHAR(C.DATA_NASCIMENTO, 'YYYY')) BETWEEN 1990 AND 1999
AND C.END_CIDADE = 'Campina Grande'
AND NF.VALOR_TOTAL = (
    SELECT MAX(NF2.VALOR_TOTAL)
    FROM NOTA_FISCAL NF2
    JOIN ORDEM_DE_COMPRA OC2 ON NF2.COD_ORDEM_COMPRA = OC2.CODORDEM
    JOIN CLIENTE C2 ON OC2.CODIGO_CLIENTE = C2.CODCLI
    WHERE TO_NUMBER(TO_CHAR(C2.DATA_NASCIMENTO, 'YYYY')) BETWEEN 1990 AND 1999
    AND C2.END_CIDADE = 'Campina Grande'
);

-- 4ª Consulta
SELECT COUNT(*)
    FROM ORDEM_DE_COMPRA
        WHERE STATUS = 'AGUARDANDO PAGAMENTO';

-- 5ª Consulta
SELECT CODNF
FROM NOTA_FISCAL
WHERE VALOR_TOTAL >= 3000 AND VALOR_TOTAL <=10000;

--6ª Consulta
SELECT DISTINCT c.NOME
FROM CLIENTE c, ORDEM_DE_COMPRA o, COMPRA_PRODUTO p
WHERE p.VALOR_ATUAL >= 500 AND p.VALOR_ATUAL <= 5000
        AND UPPER(c.END_CIDADE) LIKE '%CAMPINA GRANDE%'
        AND c.PONTOS > 100
        AND c.CODCLI = o.CODIGO_CLIENTE;
        
--7ª Consulta
SELECT NOME
    FROM PRODUTO 
        WHERE DATA_FABRICACAO >= '01-01-2019' AND
              DATA_FABRICACAO <= '12-31-2019' AND
              PRECO_VENDA >= 2000 AND
              DATA_VALIDADE >= '01-01-2022';

-- 8ª Consulta
SELECT t.NOME
FROM TRANSPORTADORA t, ORDEM_DE_COMPRA o
WHERE o.VALOR_FRETE > 100 AND o.CODIGO_TRANSPORTADORA = t.CODTRANS;

-- 9ª Consulta
SELECT C.NOME
    FROM CATEGORIA C
        WHERE (SELECT AVG(PRECO_COMPRA)
                    FROM PRODUTO
                        WHERE COD_CATEGORIA = CODCAT) > 1000;

--10ª Consulta
SELECT f.NOME
FROM FORNECEDOR f
WHERE (
  SELECT AVG(p.PRECO_VENDA)
  FROM PRODUTO p, FORNECIMENTO t
  WHERE t.CODIGO_FORNECEDOR = f.CODFORN AND p.CODPROD = t.CODIGO_PRODUTO) <= 163;

--11ª Consulta
SELECT f.NOME
FROM FORNECEDOR f
WHERE f.CODFORN IN (
    SELECT CODIGO_FORNECEDOR
    FROM FORNECIMENTO
    GROUP BY CODIGO_FORNECEDOR
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM FORNECIMENTO
        GROUP BY CODIGO_FORNECEDOR
    )
);